---
- hosts: all 
  tasks:
  - name: Fecha y Hora
    command: date
    register: fecha
  - debug: var=fecha.stdout_lines
   
  - name: Nombre Host
    command: hostname
    register: hostname
  - debug: var=hostname.stdout_lines

  - name: Servicios (Simpana)
    command: simpana {{ COMANDO }}
    register: servicios1
  - debug:
      msg: "SERVIDOR: {{ inventory_hostname }}"
      var=servicios1.stdout_lines
