---
- hosts: all 
  tasks:
  - name: Fecha y Hora
    command: date
    register: fecha
  - debug: 
      msg: "FECHA: {{ fecha.stdout }}"
      
  - name: Nombre Host
    command: hostname
    register: hostname
  - debug: 
      msg: "NOMBRE DEL HOST: {{ hostname.stdout }}"
      
  - name: Servicios (Simpana)
    command: simpana {{ COMANDO }}
    register: servicios1
  - debug: var=servicios1.stdout_lines
